POST http://localhost:4000/api/bookings
Content-Type: application/json

{
    "pickup-addres": "Aquí",
    "dropoff-address": "Allá",
    "username": "yo"

}

POST http://localhost:4000/api/bookings/123
Content-Type: application/json

{
    "action": "accept",
    "useranme":"pippin"
}